#!/bin/bash
#****h* comoonics-bootimage/ccsd-chroot
#  NAME
#    ccsd-chroot
#    $Id: ccsd-chroot,v 1.3 2010-08-06 13:35:06 marc Exp $
#  DESCRIPTION
#    Initscript for stoping and starting ccsd in chroot for
#    sharedroots
#*******
#
# ccsd   start/stop ccsd
#
# chkconfig: 345 20 80
# description: Starts and stops ccsd
#
#
### BEGIN INIT INFO
# Provides:
### END INIT INFO

CHROOT_PATH=$(/opt/atix/comoonics-bootimage/manage_chroot.sh -p) 
CHROOT_START="/opt/atix/comoonics-bootimage/manage_chroot.sh -a start_service" 
CHROOT_STATUS_PID="/opt/atix/comoonics-bootimage/manage_chroot.sh -a status_service_pid" 
CHROOT_STOP_PID="/opt/atix/comoonics-bootimage/manage_chroot.sh -a stop_service_pid" 

CCSD_OPTS=

. /etc/init.d/functions
[ -f /etc/sysconfig/cluster ] && . /etc/sysconfig/cluster

LOCK_FILE="/var/lock/subsys/ccsd-chroot"

#****f* ccsd-chroot/check_sharedroot
#  NAME
#    check_sharedroot
#  SYNOPSIS
#    function check_sharedroot {
#  MODIFICATION HISTORY
#  IDEAS
#  SOURCE
#
function check_sharedroot {
  root_fstype=$(mount | grep "/ " | awk 'BEGIN { exit_c=1; } { if ($5) { print $5; exit_c=0; } } END{ exit exit_c}')
  if [ "$root_fstype" = "gfs" ]; then
    return 1
  else
    return 0
  fi
}
#************ check_sharedroot

start()
{
  echo_local -N -n "Starting ccsd (chroot):"
  if $CHROOT_STATUS_PID /var/run/cluster/ccsd.pid ; then
  	success
  	return 0
  fi
  action $"" "$CHROOT_START ccsd $CCSD_OPTS"
}

stop()
{
  echo_local -N -n "Stopping ccsd (chroot):"
  for sec in $(seq 1 10)
    do
     if pidof ccsd > /dev/null
       then
         # get the pid of ccsd from /var/run/cluster/ccsd.pid
         # and break if the file is not there
         [ -r ${CHROOT_PATH}/var/run/cluster/ccsd.pid ] || break

         pid=$(cat ${CHROOT_PATH}/var/run/cluster/ccsd.pid )
         kill $pid 2> /dev/null || break

         sleep 1
     else
         success "shutdown"
         echo
         return 0
     fi
  done
  failure "shutdown"
  echo
  return 1
}
rtrn=1

# See how we were called.
case "$1" in
  start)
        start
        rtrn=$?
        [ $rtrn = 0 ] && touch $LOCK_FILE
        ;;

  stop)
        stop
        rtrn=$?
        [ $rtrn = 0 ] && rm -f $LOCK_FILE
        ;;

  restart)
        $0 stop
        $0 start
        rtrn=$?
        ;;

  status)
        status ccsd
        rtrn=$?
        ;;

  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        ;;
esac

exit $rtrn
