#!/bin/bash
# @(#)$File$
#
# Copyright (c) 2001 ATIX GmbH, 2007 ATIX AG.
# Einsteinstrasse 10, 85716 Unterschleissheim, Germany
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Changes to the comoonics changeroot environment and executes the given cmd.

predir=/opt/atix/comoonics-bootimage/boot-scripts
source ${predir}/etc/std-lib.sh
sourceLibs ${predir}

CHROOT_PATH=$(/opt/atix/comoonics-bootimage/manage_chroot.sh -p)

if [ $# -eq 0 ]; then
   echo "Type help to get more information.."
   echo "Type exit to continue work.."

   exec chroot $CHROOT_PATH bash --rcfile /etc/bashrc
else
   exec chroot $CHROOT_PATH bash -c "source /etc/bashrc; $*"
fi
