#!/bin/bash
#****h* comoonics-bootimage/fenced-chroot
#  NAME
#    fenced-chroot
#    $id$
#  DESCRIPTION
#    Initscript for stoping and starting fenced in chroot for
#    sharedroots
#*******
#
# chkconfig: 345 23 77
# description: Starts and stops fence domain
#
#
### BEGIN INIT INFO
# Provides:
### END INIT INFO

INITRD_DIR=/initrd
FENCE_CHROOT=/var/lib/fence_tool
FENCE_CHROOT_INITRD=/var/lib/fence_tool
FENCE_OPTS="-c -w"

. /etc/init.d/functions
[ -f /etc/sysconfig/cluster ] && . /etc/sysconfig/cluster

LOCK_FILE="/var/lock/subsys/fenced"

#****f* fenced-chroot/check_sharedroot
#  NAME
#    check_sharedroot
#  SYNOPSIS
#    function check_sharedroot {
#  MODIFICATION HISTORY
#  IDEAS
#  SOURCE
#
function check_sharedroot {
  root_fstype=$(mount | grep "/ " | awk 'BEGIN { exit_c=1; } { if ($5) { print $5; exit_c=0; } } END{ exit exit_c}')
  if [ "$root_fstype" = "gfs" ]; then
    return 1
  else
    return 0
  fi
}
#************ check_sharedroot
#****f* fenced-chroot/get_runlevel
#  NAME
#    get_runlevel
#  SYNOPSIS
#    function get_runlevel {
#  MODIFICATION HISTORY
#  IDEAS
#  SOURCE
#
function get_runlevel {
  return $(runlevel | cut -d" " -f2)
}

#************ get_runlevel
#****f* fenced-chroot/start
#  NAME
#    start
#  SYNOPSIS
#    start()
#  MODIFICATION HISTORY
#  IDEAS
#  SOURCE
#
start()
{
#  pids=$(fuser -mv ${INITRD_DIR} | grep fenced | awk '
#BEGIN{ found=1; }
#NF==5 && $5=="fenced" {print $3; found=0;}
#NF==4 && $4="fenced" {print $2; found=0;}
#END { exit found; }
#')
#  if [ $? -eq 0 ]; then
#    echo -n $"Stopping fenced from initrd"
#    kill $pids
#    if [ $? -eq 0 ]; then
##      success
#    else
#      failure
#    fi
#  el
  if [ -e ${INITRD_DIR}${FENCE_CHROOT_INITRD}/var/run/fenced.pid ] && [ ! -e /FAILURE_fenced ]; then
    echo -n $"Stopping fenced from initrd"
    kill $(cat ${INITRD_DIR}${FENCE_CHROOT_INITRD}/var/run/fenced.pid) &&
    rm -f ${INITRD_DIR}${FENCE_CHROOT_INITRD}/var/run/fenced.pid
    if [ $? -eq 0 ]; then
      success
    else
      failure
    fi
  fi

  if [ -e ${FENCE_CHROOT_INITRD}/var/run/fenced.pid ] && [ ! -e /cdsl.local/FAILURE_fenced ]; then
    stop
  fi

  echo -n "Starting fence domain (chroot):"
  if [ -e /cdsl.local/FAILURE_fenced ]; then
  	passed
  	echo
  	echo "Leaving as errors detected before"
  	rm -f /cdsl.local/FAILURE_fenced
  	exit 1
  fi

  # If gulm is in ccs, don't start fenced
  if ! [ -r /etc/cluster/cluster.conf ]
    then
      failure "/etc/cluster/cluster.conf not readable."
      echo
      return 1
  elif grep -qE "<[[:space:]]*gulm([[:space:]]|[>]|$)" \
     /etc/cluster/cluster.conf
    then
      warning "Skipping because of <gulm> section detected in " \
              "/etc/cluster/cluster.conf"
      echo
      exit 0
  fi

  rtrn=1

  if [ -e ${FENCE_CHROOT}/var/run/fenced.pid ] && [ -e /proc/$(cat ${FENCE_CHROOT}/var/run/fenced.pid) ]; then
    echo -n "Already running "$(cat ${FENCE_CHROOT}/var/run/fenced.pid)". Stop first"
    passed
    echo
    return 0
  fi
  [ -e $FENCE_CHROOT/var/run/fenced.pid ] && rm -r $FENCE_CHROOT/var/run/fenced.pid
  chroot $FENCE_CHROOT fenced ${FENCE_OPTS} > /dev/null 2>&1
  rtrn=$?

  if [ $rtrn -eq 0 ]
    then
      #> # make sure that the fence domain is up and running
      #> until grep "^Fence Domain:" /proc/cluster/services | grep -q " run "
      #> do
      #>      sleep 1;
      #> done
      success "startup"
      echo
      mount | grep $FENCE_CHROOT_SOURCE &>/dev/null
      if [ $? -eq 0 ]; then
      	mountpoint=$FENCE_CHROOT_SOURCE
      fi
      mount | grep $FENCE_CHROOT_INITRD &>/dev/null
      if [ $? -eq 0 ]; then
      	mountpoint=$FENCE_CHROOT_INITRD
      fi
      if [ -n "$mountpoint" ] ; then
        echo -n "Unmounting \"$mountpoint\" "
        umount $mountpoint
        if [ $? -eq 0 ]; then
          success
        else
          failure
        fi
        echo
      fi
  else
      failure "startup"
      echo
  fi

  # need the extra echo to properlly terminate the line
  return $rtrn
}

#************ start
#****f* fenced-chroot/stop
#  NAME
#    stop
#  SYNOPSIS
#    stop()
#  MODIFICATION HISTORY
#  IDEAS
#  SOURCE
#
stop()
{
  echo -n "Stopping fence domain (chroot):"

  if pidof fenced &> /dev/null
    then
    if [ -f $FENCE_CHROOT/var/run/fenced.pid ] && [ -e /proc/$(cat $FENCE_CHROOT/var/run/fenced.pid) ]; then
    	kill $(cat $FENCE_CHROOT/var/run/fenced.pid)
    else
    	echo -n " started from initrd "
    	kill $(cat $FENCE_CHROOT_INITRD/var/run/fenced.pid) || killproc fenced
    fi

    rtrn=$?

    if [ $rtrn -eq 0 ]
      then
      success "shutdown"
      echo
    else
      failure "shutdown"
      echo
    fi
  else
    rtrn=0
    success "shutdown"
    echo
  fi

  rm -f $FENCE_CHROOT/var/run/fenced.pid &> /dev/null
  rm -f $FENCE_CHROOT_INITRD/var/run/fenced.pid &> /dev/null
  # need the extra echo to properlly terminate the line
  return $rtrn
}
#************ stop

#****f* fenced-chroot/main
#  NAME
#    main
#  SYNOPSIS
#    main()
#  MODIFICATION HISTORY
#  IDEAS
#  SOURCE
#
rtrn=1

# See how we were called.
case "$1" in
  start)
    if [ check_sharedroot ]; then
        start
        rtrn=$?
        [ $rtrn = 0 ] && touch $LOCK_FILE
    fi
        ;;

  stop)
    if [ check_sharedroot ]; then
        stop
        rtrn=$?
        [ $rtrn = 0 ] && rm -f $LOCK_FILE
    fi
        ;;

  restart)
        $0 stop
        $0 start
        rtrn=$?
        ;;

  status)
        status fenced
        rtrn=1
        ;;

  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        ;;
esac

exit $rtrn
#************ main

#########################
# $Log: fenced-chroot,v $
# Revision 1.10  2006-08-28 16:02:22  marc
# moved creation of chroot to bootsr
#
# Revision 1.9  2006/08/14 17:43:03  marc
# bugfixes with FENCE_CHROOT and FENCE_CHROOT_SOURCE
#
# Revision 1.8  2006/08/02 12:26:23  marc
# added support for fenced on a localfs
#
# Revision 1.7  2006/05/12 13:05:50  marc
# Major Bug fixed that leaded to fenced-chroot not working when booting up.
#
# Revision 1.6  2006/05/07 11:35:34  marc
# changed fence to fenced.
#
# Revision 1.5  2006/05/03 12:47:04  marc
# added documentation
#
# Revision 1.4  2006/04/13 18:47:04  marc
# changed fence_tool to fenced to not get errors joining in the fencedomain any more
#
# Revision 1.3  2006/02/16 13:58:33  marc
# minor changes
#
# Revision 1.2  2006/01/28 15:11:21  marc
# small changes
# added cvs tags
#
