#!/bin/bash
#****h* comoonics-bootimage/preccsd
#  NAME
#    preccsd
#    $id$
#  DESCRIPTION
#*******
#
# ccsd   start/stop ccsd
#
# chkconfig: 345 19 81
# description: Starts and stops ccsd
#
#
### BEGIN INIT INFO
# Provides:
### END INIT INFO

INITRD_DIR=/initrd

. /etc/init.d/functions
[ -f /etc/sysconfig/cluster ] && . /etc/sysconfig/cluster

LOCK_FILE="/var/lock/subsys/ccsd"

#****f* preccsd/start
#  NAME
#    start
#  SYNOPSIS
#    start()
#  DESCRIPTION
#    Stops the ccsd that is running from the initrd
#
start()
{
  echo -n $"Killing ccsd:"
  (killproc ccsd && success) || failure
  rtrn=$?
  echo
  echo -n $"Relinking socket: "
  if [ $rtrn -eq 0 ]; then
    (rm -rf /var/run/cluster &&
     ln -s ${FENCE_CHROOT}/var/run/cluster /var/run/cluster &&
     success) || failure
  else
    passed
  fi
  echo
}
#************ start

#****f* preccsd/stop
#  NAME
#    start
#  SYNOPSIS
#    start()
#  DESCRIPTION
#    Umounts the bindmount /cdsl.local
#SSL23_GET_CLIENT_HELLO:unknown protocol
stop() {
#   echo "Processes running on /cdsl.local "
#   fuser -mv /cdsl.local
   return 0
}
#************ stop

#****f* preccsd/main
#  NAME
#    main
#  SYNOPSIS
#    main()
#  MODIFICATION HISTORY
#  IDEAS
#  SOURCE
#
rtrn=1

# See how we were called.
case "$1" in
  start)
        start
        rtrn=$?
        ;;

  stop)
        stop
        rtrn=$?
        ;;

  restart)
        $0 stop
        $0 start
        rtrn=$?
        ;;

  status)
        status ccsd
        rtrn=0
        ;;

  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        ;;
esac

exit $rtrn
#************ start

##################
# $Log: preccsd,v $
# Revision 1.5  2006-08-28 16:03:20  marc
# support for symlink of /var/run/cluster
#
# Revision 1.4  2006/06/07 09:42:23  marc
# *** empty log message ***
#
# Revision 1.3  2006/05/12 13:05:07  marc
# No big changes
#
# Revision 1.2  2006/05/03 12:46:58  marc
# added documentation
#
