#! /bin/sh
#****h* comoonics-bootimage/bootsr
#  NAME
#    bootsr
#    $Id: bootsr,v 1.3 2007-09-25 11:54:50 mark Exp $
#  DESCRIPTION
#    Comoonics Shared Root post boot settings
#  AUTHOR
#    Mark Hlawatschek
#
#*******
#
# chkconfig: 345 11 99
# description: do the post settings for Comoonics Shared Root
# Author: hlawatschek@atix.de
#
#

#
# /etc/rc.d/init.d/bootsr
#

CCSD_OPTS=

. /etc/init.d/functions

CCSD_LOCK_FILE="/var/lock/subsys/ccsd-chroot"
DEFAULT_LOCK_COUNT=50000
CHROOT_PATH=$(/opt/atix/comoonics-bootimage/manage_chroot.sh -p) 
UPDATE_CHROOT="/opt/atix/comoonics-bootimage/manage_chroot.sh -a update"
UMOUNT_CHROOT="/opt/atix/comoonics-bootimage/manage_chroot.sh -a umount"
MOUNT_CHROOT="/opt/atix/comoonics-bootimage/manage_chroot.sh -a mount"
BUILD_FILE="/etc/comoonics-build.txt"
VAR_RUN_FILES="cman_admin cman_client"

RETVAL=0
[ -f /etc/sysconfig/cluster ] && . /etc/sysconfig/cluster

#****f* bootsr/check_sharedroot
#  NAME
#    check_sharedroot
#  SYNOPSIS
#    function check_sharedroot
#  MODIFICATION HISTORY
#  IDEAS
#  SOURCE
#
function check_sharedroot {
  root_fstype=$(mount | grep "/ " | awk 'BEGIN { exit_c=1; } { if ($5) { print $5; exit_c=0; } } END{ exit exit_c}')
  if [ "$root_fstype" = "gfs" ]; then
    return 1
  else
    return 0
  fi
}
#************ check_sharedroot
#****f* bootsr/get_runlevel
#  NAME
#    get_runlevel
#  SYNOPSIS
#    function get_runlevel
#  MODIFICATION HISTORY
#  IDEAS
#  SOURCE
#
function get_runlevel {
  return $(runlevel | cut -d" " -f2)
}
#************ get_runlevel

#****f* bootsr/patch_halt
#  NAME
#    patch_halt
#  SYNOPSIS
#    function patch_halt
#  MODIFICATION HISTORY
#  IDEAS
#  SOURCE
#
function patch_halt {
	if ! grep "comoonics (patch v1.0)" /etc/init.d/halt > /dev/null; then
		echo "Patching halt"
		cd /etc/init.d/ && patch -f -r /tmp/halt.patch.rej > /dev/null < /opt/atix/comoonics-bootimage/patches/halt.patch
	fi
}
#************ patch_halt





#************ umount_chroot
#****f* bootsr/umount_chroot
#  NAME
#    umount_chroot
#  SYNOPSIS
#    function umount_chroot
#  MODIFICATION HISTORY
#  IDEAS
#  SOURCE
#
function umount_chroot {
  return $(runlevel | cut -d" " -f2)
}
#************ get_runlevel

#****f* bootsr/get_lockcount
#  NAME
#    get_getlockcount
#  SYNOPSIS
#    function get_lockcount default_lockcount
#  MODIFICATION HISTORY
#  IDEAS
#  SOURCE
#
function get_lockcount {
  DEF_LOCK_COUNT=$1
  MAX_LCOK_COUNT=$2
  [ -z "$DEF_LOCK_COUNT" ] && DEF_LOCK_COUNT=${DEFAULT_LOCK_COUNT}
  [ -z "$DEF_LOCK_COUNT" ] && DEF_LOCK_COUNT=50000
  [ -z "$MAX_LOCK_COUNT" ] && MAX_LOCK_COUNT=0
  cat /proc/meminfo | grep MemTotal | awk -v maxlockcount=$MAX_LOCK_COUNT -v deflockcount=$DEF_LOCK_COUNT '
  {
  	lockcount=int($2/1024/512*deflockcount);
  	if ((lockcount > maxlockcount) && (maxlockcount > 0))
  	  lockcount=maxlockcount;
  	print lockcount;
  }
'
}
#************ get_lockcount


#****f* bootsr/main
#  NAME
#    main
#  SYNOPSIS
#    function main
#  MODIFICATION HISTORY
#  IDEAS
#  SOURCE
#

# See how we were called.
case "$1" in
  start)
  	# will do
  	# - activate swap partitions (currently disabled)
  	# - mount everything except nfs (na)
  	# - update chroot environment for additional services (fence_ack_server)

    if [ check_sharedroot ]; then
      
#      runlevel=$(get_runlevel)
      echo  "Doing the Comoonics Shared Root post settings "
      touch /var/lock/subsys/bootsr
#      echo `date` Doing the Comoonics Shared Root post settings | tee -a /var/log/bootsr | logger -t com-bootsr
#      /sbin/swapon -av 2>&1 | tee -a /var/log/bootsr | logger -t com-bootsr
#      /bin/mount -at nonfs 2>&1 | tee -a /var/log/bootsr | logger -t com-bootsr
	  # Create symbolic links
	  for file in $VAR_RUN_FILES; do
	  	/bin/ln -sf $CHROOT_PATH/var/run/$file /var/run/
      done	
      # Start ccsd-chroot if it will not be started from init in Runlevel 3
      # FIXME: There will be propably be no $FENCE_CHROOT this time.
#      chkconfig --list ccsd-chroot | grep "3:on" >/dev/null 2>/dev/null
#      if [ $? -eq 1 ] && [ ! -e /var/run/cluster/ccsd.pid ]; then
#         /etc/init.d/ccsd-chroot start
#      fi
	  # Update chroot environment with files from /etc/comoonics/bootimage-chroot
	  action "Updating chroot environment" $UPDATE_CHROOT
 	  action "Mounting filesystems to chroot" $MOUNT_CHROOT
 	  
    fi
    ;;
  stop)
  	  [ -e /var/lock/subsys/bootsr ] && rm -f /var/lock/subsys/bootsr 
	  action "Cleaning up chroot environment" $UMOUNT_CHROOT
	  patch_halt
        ;;
  status)
      exit 0
      ;;
  restart|reload)
  	 stop
  	 start 
      ;;
  *)
        echo "Usage: bootsr {start|stop|status|restart|reload}"
        exit 1
esac
exit $RETVAL
#************ main
###############
# $Log: bootsr,v $
# Revision 1.3  2007-09-25 11:54:50  mark
# added functionality to create symlinks to /var/run/cman...
#
# Revision 1.2  2007/09/19 13:22:25  mark
# added method to patch /etc/init.d/halt
#
# Revision 1.1  2007/09/14 08:33:09  mark
# initial checkin
#
