#!/bin/bash
#
# $Id: linuxrc,v 1.15 2007-12-07 16:39:59 reiner Exp $
#
# @(#)$File$
#
# Copyright (c) 2001 ATIX GmbH, 2007 ATIX AG.
# Einsteinstrasse 10, 85716 Unterschleissheim, Germany
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#
# Kernelparameter for changing the bootprocess for the comoonics generic hardware detection alpha1
#    bootpart=...          Which linuxrc.{bootpart} file should be loaded into
#                  that script.
#    com-stepmode=...      If set it asks for <return> after every step
#    com-debug=...         If set debug info is output
#
# Marc Grimme: existence of /etc/gfs-lib.sh with all gfs-functions.
#         Should be the framework for all other functionalities as well.
#****h* comoonics-bootimage/linuxrc
#  NAME
#    linuxrc
#    $Id: linuxrc,v 1.15 2007-12-07 16:39:59 reiner Exp $
#  DESCRIPTION
#    The first script called by the initrd.
#*******

#****f* linuxrc/main
#  NAME
#    main
#  SYNOPSIS
#    function main() {
#  MODIFICATION HISTORY
#  IDEAS
#  SOURCE
#
# initstuff is done in here

# TODO

source /etc/boot-lib.sh
source /etc/chroot-lib.sh
source /etc/std-lib.sh

mkdir -p /proc
mount -t proc proc /proc
if cat /proc/cmdline | grep com-expert; then
	export PS1="comoonics \! > "
	/bin/bash
fi
umount /proc

distribution=$(getDistribution)
[ -e /etc/${distribution}/boot-lib.sh ] && source /etc/${distribution}/boot-lib.sh

exec 3>/dev/console
exec 4>/dev/console

initEnv

# boot parameters
#bootparms=$(getBootParameters)
#debug=$(getParm ${bootparms} 1)
#stepmode=$(getParm ${bootparms} 2)

# Print a text banner.
echo_local -en $"\t\tWelcome to "
if LC_ALL=C grep -q "Red Hat" /etc/redhat-release ; then
 [ "$BOOTUP" = "color" ] && echo -en "\\033[0;31m"
 echo_local -en "Red Hat"
 [ "$BOOTUP" = "color" ] && echo -en "\\033[0;39m"
 PRODUCT=`sed "s/Red Hat \(.*\) release.*/\1/" /etc/redhat-release`
 echo_local " $PRODUCT"
elif LC_ALL=C grep -q "Fedora" /etc/redhat-release ; then
 [ "$BOOTUP" = "color" ] && echo -en "\\033[0;31m"
 echo_local -en "Fedora"
 [ "$BOOTUP" = "color" ] && echo -en "\\033[0;39m"
 PRODUCT=`sed "s/Fedora \(.*\) release.*/\1/" /etc/redhat-release`
 echo_local " $PRODUCT"
else
 PRODUCT=`sed "s/ release.*//g" /etc/redhat-release`
 echo_local "$PRODUCT"
fi

if [ -e "$build_file" ]; then
  cat ${build_file}
fi

if [ -n "$logger" ]; then
  exec 3>$bootlog 4>$bootlog 5>/dev/null
#  exec 3>/dev/console 4>/dev/console
#  exec 5> $bootlog
  ./linuxrc.generic.sh 2>$bootlog | tee /dev/console | $logger
else
  exec 3>/dev/null 4>$bootlog
  exec 3>$bootlog
  ./linuxrc.generic.sh 2> $bootlog
fi

echo "Returned from linuxrc.generic.sh."

error_code=0
[ -e $error_code_file ] && error_code=$(cat $error_code_file)
# TODO remove lines ...
#[ -e $init_cmd_file ] && init_cmd=$(cat $init_cmd_file)
#[ -e $init_chroot_file ] && new_root=$(cat $init_chroot_file)


#echo "Init_cmd: $init_cmd, newroot: $newroot"

if [ -n "$error_code" ] && [ $error_code -eq 0 ]; then
  exec 1>&- 2>&- 3>&- 4>&- 5>&-
  exec 1>/dev/console 2>/dev/console
  switchRoot $newroot
elif [ -n "$error_code" ] && [ $error_code -eq 2 ]; then
  echo_local "Userquit falling back to bash.."
  exec 1>/dev/console 2>/dev/console /bin/bash
else
  echo_local "Error starting init-process falling back to bash."
#  /rescue.sh
  exec 1>&- 2>&- 3>&- 4>&- 5>&-
  exec 1>/dev/console 2>/dev/console
  exec /bin/bash
fi
#********** main

################
# $Log: linuxrc,v $
# Revision 1.15  2007-12-07 16:39:59  reiner
# Added GPL license and changed ATIX GmbH to AG.
#
# Revision 1.14  2007/09/18 10:06:00  mark
# added com-expert option -> start bash before linuxrc.generic.sh
#
# Revision 1.13  2007/09/07 08:03:46  mark
# bug fixes
#
# Revision 1.12  2007/08/06 15:56:14  mark
# new chroot environment
# bootimage release 1.3
#
# Revision 1.11  2007/03/09 17:57:48  mark
# added nash like switchRoot support
#
# Revision 1.10  2007/01/19 13:41:27  mark
# init_cmd uses full /var/init_cmd_file and /var/init_chroot/file content.
# Fixes bug #21
#
# Revision 1.9  2006/12/04 17:39:42  marc
# enhanced stepmode
#
# Revision 1.8  2006/06/19 15:56:13  marc
# added devicemapper support
#
# Revision 1.7  2006/06/07 09:42:23  marc
# *** empty log message ***
#
# Revision 1.6  2006/05/12 13:06:13  marc
# New redirections and other fixes.
#
# Revision 1.5  2006/05/07 11:35:05  marc
# major change to version 1.0.
# Complete redesign.
#
# Revision 1.4  2006/05/03 12:46:30  marc
# added documentation
#
